server:
  port: 8080



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{$server_ip}:3306/cangzhu
    username: root
    password: cangzhutest
  redis:
    host: {$server_ip}
    port: 6379
    password: cangzhutest
  mvc:
    servlet:
      load-on-startup: 1


netty:
  server:
    host: localhost
    port: 1972


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server_ip: