POST http://localhost:8080/login
Content-Type: application/json

{
  "account": "djm",
  "password": "djm19950818"
}

> {%
    client.global.set("token", "Bearer " + response.body.data.token);
%}

###增加用户##########
POST http://localhost:8080/user/add/user
Content-Type: application/json
Authorization: {{token}}

{
  "account": "lxq",
  "password": "whyssdydjsw555",
  "username": "titania"
}

#############
POST http://localhost:8080/user/update/passwd
Content-Type: application/json
Authorization: {{token}}

{
  "oldPassword": "123456",
  "newPassword": "djm19950818"
}

