

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.52.177.183:3306/cangzhu
    username: root
    password: cangzhutest
  redis:
    host: 106.52.177.183
    port: 6379
    password: cangzhutest
  mvc:
    servlet:
      load-on-startup: 1
  application:
    name: cangzhu-server

cz-copilot:
  jwt:
    header: Authorization
    # 默认的JwtToken过期时间，以秒为单位
    expire: 21600
    # JwtToken的加密密钥
    secret: $Cang_Zhu_Nan_Xing_By_Maple_Rain$
  cache:
    default-expire: 60

netty:
  server:
    host: localhost
    port: 1972


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

run-type:
  name: remote
